Repository yo-seobara/server, pull requests merged in 2022-10, with the labels that each got.

#68 feat: Add admin role, logged in member's information, Fix comment handling at remove post
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Member.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/MemberResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/CommentRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/CommentService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/shared/Authority.java
Labels: bug, enhancement

#69 feat: Separate APIs, Add my comment, Fix max image size
  yoseobara/src/main/java/com/final2/yoseobara/controller/CommentController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/CommentRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/PostRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/CommentService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MapService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/S3Service.java
  yoseobara/src/main/resources/application.yml
Labels: bug, enhancement

#72 feat: Add heart check in post
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/HeartRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
Labels: enhancement

#76 fix: Redirect uri, controller 수정
  yoseobara/src/main/java/com/final2/yoseobara/controller/KakaoController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/KakaoTokenDto.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/TokenProvider.java
  yoseobara/src/main/java/com/final2/yoseobara/service/KakaoMemberService.java
Labels: bug

#79 refactor: Change image processing, Add post listing by member id, Add member id in post response
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Image.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/PostRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/HeartRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/ImageRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/PostRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/S3Service.java
Labels: enhancement

#80 fix: 게시글 내 댓글 조회 시 최신순으로 정렬
  yoseobara/src/main/java/com/final2/yoseobara/controller/CommentController.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/CommentResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/CommentRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/CommentService.java
Labels: bug

#82 feat: Add image urls
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
Labels: enhancement

#87 fix: Fix duplicated api url
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
Labels: bug
