Repository yo-seobara/server, pull requests merged in 2022-09, with the labels that each got.

#16 #[2] feat: 회원가입 기능 구현
  yoseobara/src/main/java/com/final2/yoseobara/YoseobaraApplication.java
  yoseobara/src/main/java/com/final2/yoseobara/config/JwtSecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/request/MemberRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/request/TokenDto.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/response/MemberResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/response/ResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Member.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/RefreshToken.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Timestamped.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/UserDetailsImpl.java
  yoseobara/src/main/java/com/final2/yoseobara/exception/ErrorCode.java
  yoseobara/src/main/java/com/final2/yoseobara/exception/advice/CustomExceptionHandler.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/AccessDeniedHandlerException.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/AuthenticationEntryPointException.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/JwtFilter.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/TokenProvider.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/MemberRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/RefreshTokenRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/UserDetailsServiceImpl.java
  yoseobara/src/main/java/com/final2/yoseobara/shared/Authority.java
Labels: enhancement

#23 #[22] 닉네임 중복확인 기능 추가
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/request/NicknameRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/resources/application.yml
Labels: enhancement

#25 #[24] feat: cors 에러 해결
  yoseobara/src/main/java/com/final2/yoseobara/config/CorsConfig.java
  yoseobara/src/main/resources/application.yml
Labels: enhancement

#36 feat: Add image upload feature, Fix post CRUD
  .gitignore
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/advice/CustomExceptionHandler.java
  yoseobara/src/main/java/com/final2/yoseobara/config/S3Config.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/S3Controller.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/response/ResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Member.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Timestamped.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/UserDetailsImpl.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/LoginRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/MemberRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/PostRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/S3RequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/TokenDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/MemberResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/ResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/exception/ErrorCode.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/AccessDeniedHandlerException.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/AuthenticationEntryPointException.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/JwtFilter.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/TokenProvider.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/MemberRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/PostRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/S3Service.java
  yoseobara/src/main/resources/application.yml
Labels: bug, enhancement

#37 feat: Add thumbnail image creation feature
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/S3Service.java
Labels: enhancement

#39 fix: Move nickname dto
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/NicknameRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
Labels: bug

#41 feat: Add main page listing(infinite scroll, search, sorting) , Fix location type, post response dto, yml(sql)
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/PostRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/PostRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/resources/application.yml
Labels: bug, enhancement

#44 fix: Fix security url, thumbnail size, mainpage response, yml
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/S3Service.java
  yoseobara/src/main/resources/application.yml
Labels: enhancement

#46 feat: Add posts within map bounds, Add convert coordinates to address
  yoseobara/src/main/java/com/final2/yoseobara/controller/PostController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/MapRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/RGAddressDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/RGResultDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/PostRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
Labels: enhancement

#48 fix: Fix security access
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
Labels: enhancement

#49 feat: Add comment-CRUD, mapped by member, post, Fix modifiedAt in post update
  yoseobara/src/main/java/com/final2/yoseobara/controller/CommentController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Comment.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Member.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Post.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Timestamped.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/CommentRequestDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/CommentResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/CommentRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/CommentService.java
Labels: bug, enhancement

#54 feat: Add geocoding api, reverse geocoding api, FIx reverse geocoding in post
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MapController.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/MapResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/PostResponseDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/RGAddressDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/response/RGResultDto.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MapService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/PostService.java
  yoseobara/src/main/resources/application.yml
Labels: enhancement

#62 feat: 카카오 소셜로그인 기능 구현
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/KakaoController.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/MemberController.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/Member.java
  yoseobara/src/main/java/com/final2/yoseobara/domain/UserDetailsImpl.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/KakaoTokenDto.java
  yoseobara/src/main/java/com/final2/yoseobara/dto/request/KakaoUserInfoDto.java
  yoseobara/src/main/java/com/final2/yoseobara/jwt/TokenProvider.java
  yoseobara/src/main/java/com/final2/yoseobara/repository/MemberRepository.java
  yoseobara/src/main/java/com/final2/yoseobara/service/KakaoMemberService.java
  yoseobara/src/main/java/com/final2/yoseobara/service/MemberService.java
  yoseobara/src/main/resources/templates/login.html
Labels: enhancement

#65 fix: redirect_uri 수정, 테스트용코드 삭제
  yoseobara/build.gradle
  yoseobara/src/main/java/com/final2/yoseobara/config/SecurityConfiguration.java
  yoseobara/src/main/java/com/final2/yoseobara/controller/KakaoController.java
  yoseobara/src/main/java/com/final2/yoseobara/service/KakaoMemberService.java
  yoseobara/src/main/resources/templates/login.html
Labels: bug
